---
title: "Modeling"
author: "Aleksei Sorokin, asorokin@hawk.iit.edu, A20394300"
date: "3/12/2020"
output: pdf_document
---

## Load Data
```{r}
df <- read.csv('data/all_coaches.csv')
head(df)
```

## Split into train test datasets
```{r}
set.seed(7)
train_frac <- 4/5
df_HOF_1 <- df[df$HOF==1,]
df_HOF_0 <- df[df$HOF==0,]
HOF_1_train <- sample(1:nrow(df_HOF_1),floor(nrow(df_HOF_1)*train_frac))
HOF_0_train <- sample(1:nrow(df_HOF_0),floor(nrow(df_HOF_0)*train_frac))
df_train <- rbind(df_HOF_1[HOF_1_train,],df_HOF_0[HOF_0_train,])
df_test <- rbind(df_HOF_1[-HOF_1_train,],df_HOF_0[-HOF_0_train,])
l1 <- sprintf('Train Fractio:n %.2f',train_frac)
l2 <- sprintf('Hall of Fame Coaches: %d. (Train %d , Test %d)',
        nrow(df_HOF_1),length(HOF_1_train),nrow(df_HOF_1)-length(HOF_1_train))
l3 <- sprintf('Non Hall of Fame Coaches: %d. (Train %d , Test %d)',
        nrow(df_HOF_0),length(HOF_0_train),nrow(df_HOF_0)-length(HOF_0_train))
l4 <- sprintf('Overall: (Train %d , Test %d)',nrow(df_train),nrow(df_test))
cat(sprintf('%s\n%s\n%s\n%s\n',l1,l2,l3,l4))
```

## Standard Logistic Regression Model
```{r}
model_1 <- glm(HOF ~ GR + PGR + CC + Sport,#GR+WL.+PGR+PWL.+CC+C+Sport,
               data=df_train,
               family="binomial")
summary(model_1)
df_test$yHat_1 <- predict(model_1, newdata=df_test, type="response")
```

## Logistic Mixed Model
```{r message=F}
library(lme4)
model_2 <- lmer(HOF ~ GR + PGR + CC + (1|Sport),#GR + WL. + PGR + PWL. + CC + C + (1 | Sport),
                data = df_train)
summary(model_2)
df_test$yHat_2 <- predict(model_2,df_test, type="response")
```

## Bayesian Logistic Mixed Model
```{r}
library(blme)
model_3 <- blmer(HOF ~ GR + PGR + CC + (1|Sport),# GR + WL. + PGR + PWL. + CC + C + (1 | Sport),
                 data = df_train,
                 resid.prior = gamma,
                 fixef.prior = normal,
                 cov.prior = wishart)
summary(model_3)
df_test$yHat_3 <- predict(model_3, newdata=df_test, type="response")
```

## Make predictions on test data and calculate metrics
```{r}
model_metrics <- function(df_test,yHat_col,model_name){
  yHat_b_col <- paste0(yHat_col,'b')
  df_test[,yHat_b_col] <-(df_test[[yHat_col]] >= .5)
  yHat_b <- df_test[[yHat_b_col]]
  hof <- df_test$HOF
  tp <- sum((yHat_b==1 & hof==1))
  fp <- sum((yHat_b==1 & hof==0))
  fn <- sum((yHat_b==0 & hof==1))
  tn <- sum((yHat_b==0 & hof==0))
  accuracy <- (tp+tn)/(tp+tn+fp+fn)
  precision <- tp/(tp+fp)
  recall <- tp/(tp+fn)
  cat(sprintf('%s\n\tAccuracy: %.3f\n\tPrecision: %.3f\n\tRecall: %.3f\n',
              model_name,accuracy,precision,recall))
  return (df_test)}
```

## Compare models
```{r}
df_test <- model_metrics(df_test,'yHat_1','Standard Logistic Regression')
df_test <- model_metrics(df_test,'yHat_2','Logistic Mixed Model')
df_test <- model_metrics(df_test,'yHat_3','Bayesian Mixed Model')
head(df_test[df_test$HOF==1,])
```